### ISSUE TITLE
No ability to install guest tools on ubuntu guests?

### ISSUE THREAD

**Issue by mzealey** [libguestfs/virt-v2v#4]
Looking at https://github.com/libguestfs/virt-v2v/blob/8cf4488d6bcde8dd0b84c199c96ff5763e6a08fa/v2v/windows_virtio.ml#L187-L198 it seems like there is no possibility to support ubuntu guests?

I am getting the following in centos 8 virt-v2v:

```
virt-v2v: warning: don't know how to install guest tools on ubuntu-20
```

I'd have thought just looking at the directories for that code to see if there is something there would be a reasonable generic solution?

**Comment by nertpinx** [comment]
Converting Ubuntu guests should be fine, the warning you see just tells you that virt-v2v does not know how to make sure qemu guest agent is installed. I cannot 100% confirm where the message comes from as I could not find where it comes from. I do not fully understand some of the code paths despite looking at it for quite some time now. I think you might be using an older version and there has been some changes.
In order to further this discussion I suggest sending an e-mail to the ML ( https://www.redhat.com/mailman/listinfo/libguestfs ) which should work even without subscribing there IIRC (although, as usual, subscribing skips the moderator approvals for incoming mail).
Last, but not least, if you just want to proceed, then this warning does not mean much if you make sure qemu guest agent is installed in the guest.
Hope that helps, have a nice day.
